export const GET_DATA_REQUEST_WAS_RECIEVED = "GET_DATA_REQUEST_WAS_RECIEVED";
export const GET_DATA_REQUEST_ERROR = "GET_DATA_REQUEST_ERROR";
export const GET_DATA_ITEM_REQUEST_WAS_RECIEVED = "GET_DATA_ITEM_REQUEST_WAS_RECIEVED";
